const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'index.html');
let text = fs.readFileSync(filePath, 'utf8');
const replacement = `        // Replace the existing \\`const m = [...]\\` definition with the full menu (added missing categories/items).
        const m = [
  /* BREAKFAST MENU (Per Guest) */
  { n: "Breakfast Option 1", d: "Tea Station, Juice Station, Water Station, Muffins, Sliced Bread, Chicken Spring Roll, Sausage, and Meat Pie", p: 10500, c: "Breakfast" },
  { n: "Breakfast Option 2", d: "Tea Station, Natural Fruit Juice, Cinnamon Rolls, Scotch Egg, Doughnuts, and Peppered Wings", p: 8500, c: "Breakfast" },
  { n: "Breakfast Option 3", d: "Sliced Bread, Sausage, Scrambled Egg, Boiled Yam, Boiled Plantain, Pap, Egg Sauce, Water Station, and Juice Station", p: 11500, c: "Breakfast" },
  { n: "Breakfast Option 4", d: "Tea Station, Juice Station, Water Station, Ewa Agoyin, Buttered Bread Roll, Sliced Bread, Mackerel Sauce, Tapioca, Custard, Fruits Cups, Cup Cakes, and Sandwich", p: 13000, c: "Breakfast" },

  /* SMALL CHOPS OPTIONS */
  { n: "Small Chops Option 1", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 4 Puff Puff, 1 BBQ Chicken", p: 2500, c: "Small Chops" },
  { n: "Small Chops Option 2", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 4 Puff Puff, 1 BBQ Chicken, 1 Corn Dog", p: 2800, c: "Small Chops" },
  { n: "Small Chops Option 3", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 4 Puff Puff, 1 BBQ Chicken, and Peppered Gizzard", p: 3000, c: "Small Chops" },
  { n: "Small Chops Option 4", d: "1 Mayo Prawn Roll, 1 Samosa, 4 Mosa, 4 Puff Puff, 1 BBQ Chicken", p: 4000, c: "Small Chops" },
  { n: "Small Chops Option 5", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 5 Puff Puff, 1 BBQ Chicken, 1 Battered Fish", p: 3200, c: "Small Chops" },
  { n: "Small Chops Option 6", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 5 Puff Puff, 1 BBQ Chicken, 1 Peppered Gizzard, 1 Corn Dog, 1 Stick Meat", p: 4000, c: "Small Chops" },
  { n: "Small Chops Option 7", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 5 Puff Puff, 1 BBQ Chicken, 1 Prawn", p: 4000, c: "Small Chops" },
  { n: "Small Chops Option 8", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 5 Puff Puff, 1 BBQ Chicken, 1 Peppered Snail", p: 4200, c: "Small Chops" },
  { n: "Small Chops Option 9", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 5 Puff Puff, 1 BBQ Chicken, 1 Prawn, 1 Buttered Parsley Corn, 1 Peppered Gizzard", p: 5500, c: "Small Chops" },
  { n: "Small Chops Option 10", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 5 Puff Puff, 1 BBQ Chicken, 1 Peppered Snail, 1 Peppered Gizzard", p: 5000, c: "Small Chops" },
  { n: "Small Chops Option 11", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 5 Puff Puff, 1 BBQ Chicken, 1 Peppered Snail, 1 Corn Dog", p: 5000, c: "Small Chops" },
  { n: "Small Chops Option 12", d: "1 Spring Roll, 1 Samosa, 4 Mosa, 5 Puff Puff, 1 BBQ Chicken, 1 Peppered Snail, 1 Prawn", p: 6000, c: "Small Chops" },
  { n: "Small Chops Option 13", d: "1 Chicken Lollipop, 1 Fish Cake, 5 Puff Puff, 1 Yam Ball, 1 Samosa, 1 Peppered Wings/Sweet Wings, 1 Buttered Parsley Corn", p: 5400, c: "Small Chops" },
  { n: "Small Chops Option 14", d: "1 Beefy Spring Roll, 1 Chicken Money Bag, 4 Mosa, 5 Puff Puff, 1 BBQ Chicken/Peppered Wings, 1 Battered Fish, 1 Prawn Tempura, 1 Corn Dog", p: 6000, c: "Small Chops" },
  { n: "Small Chops Option 15", d: "1 Chicken Spring Roll, 1 Chicken Money Bag, 1 Peppered Gizzard, 1 Buttered Parsley Corn, 1 Peppered Wing, 4 Mosa, 5 Puff Puff", p: 6000, c: "Small Chops" },

  /* MINI EATS */
  { n: "Jolly Jollof", d: "Smokey Jollof Rice x Peppered Chicken Lollipop", p: 4500, c: "Mini Eats" },
  { n: "Eko Dun", d: "Steamed White Rice with 229 Signature Ayilata Sauce & Boiled Eggs", p: 4500, c: "Mini Eats" },
  { n: "Stir Fry Shrimp Pasta", d: "Stir Fry Shrimp Pasta", p: 5500, c: "Mini Eats" },
  { n: "Tomato Pasta with Spicy Meatballs", d: "Tomato Pasta with Spicy Meatballs", p: 4500, c: "Mini Eats" },
  { n: "Alfredo Pasta", d: "Alfredo Pasta", p: 6000, c: "Mini Eats" },
  { n: "Awolowo", d: "Smoked Yaji Spiced Guinea Fowl Cutlets, French Fries, Corn", p: 5500, c: "Mini Eats" },
  { n: "Peri-Peri", d: "Peri Wings/Peri Turkey Cutlets et Fries x Sausage", p: 5500, c: "Mini Eats" },
  { n: "Ofada Medley", d: "Ofada Rice with Meaty Ayamase Sauce x Boiled Eggs", p: 4000, c: "Mini Eats" },
  { n: "Lavida Local", d: "Peppered Rice Infused with Smoked Fish, Shrimp, Ponmo with Peppered Turkey Cutlet", p: 5000, c: "Mini Eats" },
  { n: "Fried Rice", d: "Beef/Shrimp Fried Rice with Crispy Fish or Sweet Chilli Wings", p: 5000, c: "Mini Eats" },
  { n: "Mini Onjowo", d: "Mini Abula, Gbegiri, Ewedu & Assorted Meat", p: 4000, c: "Mini Eats" },
  { n: "Oliver Twist", d: "Nigerian Stir Fry Pasta Infused with Asun", p: 5000, c: "Mini Eats" },

  /* CANAPÉS */
  { n: "Veggies Roll", d: "Veggies Roll with Sweet Chilli Dip", p: 2000, c: "Canapes" },
  { n: "Crispy Yam / Potato Balls", d: "Crispy Yam / Potato Balls with Spicy Sauce Toppings", p: 2000, c: "Canapes" },
  { n: "Mozzarella Cheese Meatballs", d: "Mozzarella Cheese Meatballs", p: 2000, c: "Canapes" },
  { n: "Bruschetta (Chicken Pesto & Basil)", d: "Bruschetta with Chicken Pesto & Basil", p: 2000, c: "Canapes" },
  { n: "Yamarita", d: "Yamarita with Saucy Dip", p: 2000, c: "Canapes" },
  { n: "Gourmet Cheese Springroll / Samosa", d: "Gourmet Cheese Springroll / Samosa", p: 2000, c: "Canapes" },
  { n: "Crudités", d: "Crudités", p: 2000, c: "Canapes" },
  { n: "Mini Vegetable Sandwiches", d: "Mini Vegetable Sandwiches", p: 2000, c: "Canapes" },
  { n: "Thai Chicken Salad", d: "Thai Chicken Salad with Dressing", p: 2000, c: "Canapes" },
  { n: "Spicy Prawn Springroll", d: "Spicy Prawn Mayonnaise Springroll", p: 2000, c: "Canapes" },
  { n: "Chicken Croquettes", d: "Chicken Croquettes", p: 2500, c: "Canapes" },
  { n: "Smoked Chicken on Toasted Bun", d: "Smoked Chicken on a Toasted Bun Bed", p: 2500, c: "Canapes" },
  { n: "Bruschetta (Mayo Shrimps)", d: "Bruschetta with Mayo Shrimps", p: 2500, c: "Canapes" },
  { n: "Meatball Trio", d: "Meatball Trio", p: 2500, c: "Canapes" },
  { n: "Mini Club Sandwiches", d: "Mini Club Sandwiches", p: 2500, c: "Canapes" },
  { n: "Gourmet Puff Puff", d: "Gourmet Puff Puff", p: 2500, c: "Canapes" },
  { n: "Shrimps Puff Puff", d: "Shrimps Puff Puff with Coconut Flakes", p: 2500, c: "Canapes" },
  { n: "Spicy Beef Skewers", d: "Spicy Beef Skewers", p: 2500, c: "Canapes" },
  { n: "Mini Chicken Wrap", d: "Mini Chicken Wrap", p: 2500, c: "Canapes" },
  { n: "Chicken Lollipop", d: "Chicken Lollipop", p: 2500, c: "Canapes" },
  { n: "Fish Balls", d: "Fish Balls", p: 2500, c: "Canapes" },
  { n: "Suya Sticks", d: "Suya Sticks", p: 2500, c: "Canapes" },
  { n: "Cocktail Gizdodo", d: "Cocktail Gizdodo", p: 2500, c: "Canapes" },
  { n: "Fish Cakes", d: "Fish Cakes with Sweet Cucumber Dips", p: 2500, c: "Canapes" },
  { n: "Tacos (Beef)", d: "Tacos (Beef)", p: 2500, c: "Canapes" },
  { n: "Tacos (Chicken)", d: "Tacos (Chicken)", p: 2500, c: "Canapes" },
  { n: "Spicy Honey Chicken Wings", d: "Spicy Honey Chicken Wings", p: 2500, c: "Canapes" },
  { n: "Sweet Chilli Chicken Wings", d: "Sweet Chilli Chicken Wings", p: 2500, c: "Canapes" },
  { n: "Corn Floater", d: "Corn Floater", p: 2500, c: "Canapes" },
  { n: "Shrimps Toast", d: "Shrimps Toast", p: 2500, c: "Canapes" },
  { n: "Chicken Popcorn", d: "Chicken Popcorn with Sweet Chilli Dip", p: 2500, c: "Canapes" },
  { n: "Prawn Tempura", d: "Prawn Tempura with Dip", p: 3000, c: "Canapes" },
  { n: "Coconut Crusted Prawn", d: "Coconut Crusted Prawn Served with Dip", p: 3000, c: "Canapes" },
  { n: "Prawn Cocktail / Shot", d: "Prawn Cocktail / Shot", p: 3000, c: "Canapes" },
  { n: "Jerk Chicken Skewers", d: "Jerk Chicken Skewers", p: 3000, c: "Canapes" },
  { n: "Lobster Roll", d: "Lobster Roll", p: 3000, c: "Canapes" },
  { n: "Crunchy Hotdog", d: "Crunchy Hotdog", p: 3000, c: "Canapes" },
  { n: "Mini Gourmet Burger", d: "Mini Gourmet Burger", p: 3500, c: "Canapes" },
  { n: "Crispy Chicken Slaw Sliders", d: "Crispy Chicken with Slaw Sliders", p: 3500, c: "Canapes" },
  { n: "Mini Pulled BBQ Chicken Burger", d: "Mini Pulled BBQ Chicken Burger with Purple Slaw", p: 3500, c: "Canapes" },
  { n: "Cheese & Ham Toast", d: "Cheese & Ham Toast with Hot Chocolate", p: 3500, c: "Canapes" },
  { n: "Lamb Cutlet", d: "Lamb Cutlet Served with Yoghurt Drill Dip", p: 3500, c: "Canapes" },
  { n: "Salmon Caviar Crostini", d: "Salmon Caviar with Cream Cheese on Crostini", p: 3500, c: "Canapes" },
  { n: "Asun Crostini", d: "Asun Crostini", p: 3500, c: "Canapes" },
  { n: "Buttered Garlic King Prawn", d: "Buttered Garlic King Prawn with Spicy Dip", p: 3500, c: "Canapes" },
  { n: "Oat Cake with Crispy Chicken", d: "Oat Cake with Crispy Chicken", p: 3500, c: "Canapes" },
  { n: "Potato Wedges with Spicy Wings", d: "Potato Wedges with Spicy Chicken Wings", p: 3500, c: "Canapes" },
  { n: "Ewa Agoyin", d: "Ewa Agoyin with Bread & Sauce", p: 3500, c: "Canapes" },
  { n: "Prawn Shot", d: "Prawn Shot", p: 4500, c: "Canapes" },
  { n: "Mini Pasta Cups", d: "Mini Pasta Cups", p: 4500, c: "Canapes" },
  { n: "Coconut Prawn with Spicy Dip", d: "Coconut Prawn with Spicy Dip", p: 4500, c: "Canapes" },
  { n: "Muffins", d: "Muffins", p: 4500, c: "Canapes" },
  { n: "Mini Fruit Cups", d: "Mini Fruit Cups", p: 4500, c: "Canapes" },
  { n: "Sweet Chili Wings", d: "Sweet Chili Wings", p: 3500, c: "Canapes" },
  { n: "Chicken Lollipop with Sweet Dip", d: "Chicken Lollipop with Sweet Dip", p: 3500, c: "Canapes" },
  { n: "Honey Glazed Wings", d: "Honey Glazed Wings", p: 3500, c: "Canapes" },
  { n: "Meatballs Trio", d: "Meatballs Trio", p: 3500, c: "Canapes" },
  { n: "Shrimp Skewers", d: "Shrimp Skewers", p: 3500, c: "Canapes" },
  { n: "Mini Chicken Burger with Purple Slaw", d: "Mini Chicken Burger with Purple Slaw", p: 3500, c: "Canapes" },
  { n: "Plantain Cups", d: "Plantain Cups", p: 3500, c: "Canapes" },
  { n: "Mayo Prawn Roll with Sweet Chilli Dip", d: "Mayo Prawn Roll with Sweet Chilli Dip", p: 3000, c: "Canapes" },
  { n: "Condensed Milk Puff Puff Skewers", d: "Condensed Milk Puff Puff Skewers", p: 3000, c: "Canapes" },
  { n: "Crispy Tuna Fish Sweet Potato Ball", d: "Crispy Tuna Fish Sweet Potato Ball", p: 3000, c: "Canapes" },
  { n: "Yam Ball with Sweet Topping", d: "Yam Ball with Sweet Topping", p: 3000, c: "Canapes" },
  { n: "Sandwich", d: "Sandwich", p: 3000, c: "Canapes" },
  { n: "Mini Gizdodo", d: "Mini Gizdodo", p: 3000, c: "Canapes" },
  { n: "Ram Roll", d: "Ram Roll", p: 3000, c: "Canapes" },
  { n: "Hotdog", d: "Hotdog", p: 3000, c: "Canapes" },
  { n: "Mini Burger", d: "Mini Burger", p: 3000, c: "Canapes" },
  { n: "Puff Puff Dessert with Oreo Topping", d: "Puff Puff Dessert with Oreo Topping", p: 3000, c: "Canapes" },

  /* GRILLS */
  { n: "Turkey Cutlet", d: "Turkey Cutlet", p: 6000, c: "Grills" },
  { n: "Croaker Fish Cutlet", d: "Croaker Fish Cutlet", p: 6000, c: "Grills" },
  { n: "Catfish Cutlet", d: "Catfish Cutlet", p: 5500, c: "Grills" },
  { n: "Whole Croaker Fish", d: "Whole Croaker Fish", p: 12000, c: "Grills" },
  { n: "Whole Catfish", d: "Whole Catfish", p: 11000, c: "Grills" },
  { n: "Local Chops", d: "Local Chops", p: 4000, c: "Grills" },
  { n: "Kebabs", d: "Kebabs", p: 5500, c: "Grills" },
  { n: "Suya", d: "Suya", p: 3500, c: "Grills" },
  { n: "Snail & Prawn Combo", d: "Snail & Prawn Combo", p: 20000, c: "Grills" },
  { n: "Chicken Shawarma", d: "Chicken Shawarma", p: 6000, c: "Grills" },
  { n: "Beef Shawarma", d: "Beef Shawarma", p: 6000, c: "Grills" },
  { n: "Chicken Shawarma with Sausage", d: "Chicken Shawarma with Sausage", p: 5000, c: "Grills" },
  { n: "Beef Shawarma with Sausage", d: "Beef Shawarma with Sausage", p: 5000, c: "Grills" },
  { n: "Chicken Cutlet", d: "Chicken Cutlet", p: 5500, c: "Grills" },
  { n: "Chicken Whole Lap", d: "Chicken Whole Lap", p: 10500, c: "Grills" },
  { n: "Chicken Burger", d: "Chicken Burger", p: 4500, c: "Grills" },
  { n: "Beef Burger", d: "Beef Burger", p: 4500, c: "Grills" },
  { n: "Wings", d: "Wings", p: 5500, c: "Grills" },
  { n: "Hotdog x Fries", d: "Hotdog x Fries", p: 4000, c: "Grills" },
  { n: "Titus Fish x Roasted Plantain", d: "Titus Fish x Roasted Plantain", p: 5000, c: "Grills" },
  { n: "Jumbo Snails Platter", d: "Jumbo Snails Platter", p: 7500, c: "Grills" },
  { n: "Smoked Yaji Guinea Fowl", d: "Smoked Yaji Guinea Fowl", p: 6000, c: "Grills" },

  /* SIDES */
  { n: "Roasted Plantain", d: "Roasted Plantain", p: 1500, c: "Sides" },
  { n: "Corn on Cob", d: "Corn on Cob", p: 1000, c: "Sides" },
  { n: "Buttered Parsley Corn", d: "Buttered Parsley Corn", p: 1000, c: "Sides" },
  { n: "Yam Fries", d: "Yam Fries", p: 1200, c: "Sides" },
  { n: "Plantain Fries", d: "Plantain Fries", p: 1200, c: "Sides" },
  { n: "Sweet Potato Fries", d: "Sweet Potato Fries", p: 1200, c: "Sides" },
  { n: "French Fries", d: "French Fries", p: 2000, c: "Sides" },
  { n: "Sausage", d: "Sausage", p: 1000, c: "Sides" },

  /* LARGE PLATTERS PACKAGES */
  { n: "Abby's Platter", d: "Abby's Platter", p: 14500, c: "Platters" },
  { n: "Chic-Choc", d: "Chic-Choc", p: 26500, c: "Platters" },
  { n: "Dekunle", d: "Dekunle", p: 30000, c: "Platters" },
  { n: "Delight", d: "Delight", p: 40000, c: "Platters" },
  { n: "Silver", d: "Silver", p: 43500, c: "Platters" },
  { n: "Lasgidi", d: "Lasgidi", p: 45000, c: "Platters" },
  { n: "Classic", d: "Classic", p: 50000, c: "Platters" },
  { n: "Lavish", d: "Lavish", p: 51000, c: "Platters" },
  { n: "Abike", d: "Abike", p: 53000, c: "Platters" },
  { n: "Gold", d: "Gold", p: 62000, c: "Platters" },
  { n: "Supper", d: "Supper", p: 63000, c: "Platters" },
  { n: "Odowgu", d: "Odowgu", p: 70000, c: "Platters" },

  /* MEATY (WHOLE LIVESTOCK) */
  { n: "Asun (Whole Goat)", d: "Asun (Whole Goat)", p: 200000, c: "Meaty" },
  { n: "Ram Suya (Whole Ram)", d: "Ram Suya (Whole Ram)", p: 600000, c: "Meaty" },
  { n: "Cow Suya (Whole Cow)", d: "Cow Suya (Whole Cow)", p: 1600000, c: "Meaty" },
  { n: "Service Fee - Goat", d: "Service Fee (Client provides animal)", p: 80000, c: "Meaty" },
  { n: "Service Fee - Ram", d: "Service Fee (Client provides animal)", p: 200000, c: "Meaty" },
  { n: "Service Fee - Cow", d: "Service Fee (Client provides animal)", p: 600000, c: "Meaty" }
];`;
const regex = /const m = \[[\s\S]*?\];/;
if (!regex.test(text)) {
  console.error('Menu array block not found');
  process.exit(1);
}
text = text.replace(regex, replacement);
fs.writeFileSync(filePath, text, 'utf8');
console.log('Menu block replaced.');
